[Unit]
Requires=archpad-hexagonrpcd-sdsp.service
After=archpad-hexagonrpcd-sdsp.service

[Service]
Restart=always
RestartSec=2s
TimeoutStartSec=130
ExecStartPre=/usr/lib/archpad/archpad-wait-ssc
ExecStartPost=/usr/lib/archpad/archpad-wait-sensor-proxy
