# ArchPad mkinitcpio configuration for Xiaomi Pad 6 (pipa)
MODULES=(loop ufs_qcom ufshcd_core ufshcd_pltfrm)
BINARIES=(losetup)
FILES=()
HOOKS=(base udev autodetect modconf kms keyboard keymap consolefont block archpad-userdata filesystems fsck)
